[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-mountain1Purple
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-mountain1Purple
GtkTheme=oomox-mountain1Purple
IconTheme=oomox-mountain1Purple
MetacityTheme=oomox-mountain1Purple
